#!/bin/bash
set -e

chown -R mysql:mysql /var/lib/mysql
mysql_install_db --user mysql > /dev/null

#MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-""}
#MYSQL_DATABASE=${MYSQL_DATABASE:-""}
#MYSQL_USER=${MYSQL_USER:-""}
#MYSQL_PASSWORD=${MYSQL_PASSWORD:-""}
MYSQLD_ARGS=${MYSQLD_ARGS:-""}

tfile=`mktemp`
if [[ ! -f "$tfile" ]]; then
    return 1
fi

cat << EOF > $tfile
USE mysql;
FLUSH PRIVILEGES;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;

UPDATE user SET password=PASSWORD("dont_use_root_user") WHERE user='root';

UPDATE user SET password=PASSWORD("") WHERE user='drupal';
CREATE DATABASE IF NOT EXISTS \`drupal\` CHARACTER SET utf8 COLLATE utf8_general_ci;
GRANT ALL ON \`drupal\`.* to 'drupal'@'%' IDENTIFIED BY '';
EOF

/usr/sbin/mysqld --bootstrap --verbose=0 $MYSQLD_ARGS < $tfile
rm -f $tfile

exec /usr/sbin/mysqld $MYSQLD_ARGS
